flowchart LR
    BASE[BASE
Loopback 192.168.1.1/32] ---|10.0.1.0/30
Cost 10| ALFA[HELI-ALFA
Loopback 192.168.2.1/32]
    ALFA ---|10.0.2.0/30
Cost 10| BRAVO[HELI-BRAVO
Loopback 192.168.3.1/32]
    BRAVO ---|10.0.3.0/30
Cost 50| CHARLIE[HELI-CHARLIE
Loopback 192.168.4.1/32]
    CHARLIE ---|10.0.4.0/30
Cost 50| BASE
